### ISSUE TITLE
Is there an option to disable Windows Mixed Reality under Linux or macOS (Hackintosh)?

### ISSUE THREAD

**Issue by HoshiYamazaki** [OpenHMD/OpenHMD#214] opened 2019-04-01 19:40 UTC
As title says.

**Comment by TheOnlyJoey** [comment] 2019-04-02 11:08
I don't really understand what you mean, OpenHMD is a driver for a wide range of devices http://www.openhmd.net/index.php/devices/ and we also support WMR. Why would you want to disable WMR?

**Comment by HoshiYamazaki** [comment] 2019-04-02 15:26
I want to disable it because macOS detects it as normal display which is causing for example problems because sometimes programs opens under it or cursor is moved to WMR screen.

I heard that macOS detects Rift or Vive and disables them, but not WMR, so I had idea somebody here knows how to do that.

**Comment by TheOnlyJoey** [comment] 2019-04-02 15:28
Since OSX has no support for direct mode, it appearing a a regular display is actually a good thing, since if it would be disabled, it would not be usable, since no applications can use the display (since there would be no driver)

**Comment by Wallbraker** [comment] 2019-04-02 15:30
We can't really help you with macOS unfortunately, you will to file a issue with Apple.

The "proper" thing to do for Linux is submit a quirk patch for the Linux kernel to force non-desktop on for these headsets. Or you can use, before or after plugging it in, (if you have a new enough Xorg installed).

```bash
xrandr --output <OUTPUT> --set non-desktop 1
```

**Comment by Wallbraker** [comment] 2019-04-02 15:38
@HoshiYamazaki I'm getting some conflicting info, when you connect a Vive or a Rift is the desktop extended to that display (Even if the display is black)?

**Comment by HoshiYamazaki** [comment] 2019-04-02 17:58
> @HoshiYamazaki I'm getting some conflicting info, when you connect a Vive or a Rift is the desktop extended to that display (Even if the display is black)?

No, from what I heard from redditit behave normally, just in case of Windows Mixed Reality it gets buggy and extends display to it, there is no native support of WMR in macOS and it's shame :/ I only own Lenovo Explorer, sorry for my english causing misunderstanding.

**Comment by TheOnlyJoey** [comment] 2019-04-03 11:19
Well with OpenHMD you would be able to use OpenHMD supported applications. Extending displays is not 'buggy' but intended behavior (called Extended Mode), something that most OpenHMD applications use so far. Closing for not being a bug/issue.

**Closed by TheOnlyJoey** 2019-04-03 11:19 UTC
