### ISSUE TITLE
Android Tracking Support

### ISSUE THREAD

**Issue by noname22** [OpenHMD/OpenHMD#26] opened 2014-11-22 14:16 UTC
Support for using the native Android API sensors as input for OpenHMDs head tracking.

**Comment by TheOnlyJoey** [comment] 2015-08-26 20:26
Since this is going strong on the android branch (https://github.com/OpenHMD/OpenHMD/tree/android) maybe close this?

**Comment by noname22** [comment] 2015-08-27 07:38
It's probably best to close the issue once the feature branch has been merged.

**Comment by TheOnlyJoey** [comment] 2016-02-08 12:40
After migration and some fixes here and there, everything seems to work as intended with the exception of constant drift.

This is probably due to the lack of sensor calibration, after adding this, implementation is complete.

**Comment by TheOnlyJoey** [comment] 2018-10-20 12:57
This is actually working for a while now!

**Closed by TheOnlyJoey** 2018-10-20 12:57 UTC
Labels: Android, enhancement
